### ISSUE TITLE
D3Graph UnicodeEncodeError: error

### ISSUE THREAD

**Issue by nsankar** [erdogant/hnet#3]
Firstly, thanks for developing this great library. In Windows 10 with python 3.9 version, for the following part of hnet, 

results = hn.association_learning(df)
G = hn.d3graph()

I get this UnicodeEncodeError: issue as given below. Looks like you might have to do utf-8 encoding somewhere in the d3graph code ? ([something of this sort](https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters))

`192     # Final
    193     out = dict()

~\AppData\Local\Programs\Python\Python39\lib\site-packages\d3graph\d3graph.py in _write_index_html(config, json_data)
    274     index_file = Path(config['savepath'])
    275     print('Writing %s' % index_file.absolute())
--> 276     index_file.write_text(index_template.render(content))
    277 
    278 

~\AppData\Local\Programs\Python\Python39\lib\pathlib.py in write_text(self, data, encoding, errors)
   1273                             data.__class__.__name__)
   1274         with self.open(mode='w', encoding=encoding, errors=errors) as f:
-> 1275             return f.write(data)
   1276 
   1277     def readlink(self):

~\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py in encode(self, input, final)
     17 class IncrementalEncoder(codecs.IncrementalEncoder):
     18     def encode(self, input, final=False):
---> 19         return codecs.charmap_encode(input,self.errors,encoding_table)[0]
     20 
     21 class IncrementalDecoder(codecs.IncrementalDecoder):

UnicodeEncodeError: 'charmap' codec can't encode character '\u03b5' in position 44258: character maps to <undefined>`

**Comment by erdogant** [comment]
Thanks for pointing this out!
It seems that jinja2 has a new update which throws an error. I fixed the jinja2 issue by freezing it to version 2.11.3.
Can you reinstall d3graph and check whether this solves your issue?

```
pip install -U d3graph
import d3graph
print(d3graph.__version__)

```
The version should be >= 0.1.12

**Comment by nsankar** [comment]
@erdogant It works . Thanks.

**Comment by marvensherif** [comment]
same error and it doesn't work 

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
Writing C:\Users\marve\Desktop\Term9\Graduation Project\index.html
Traceback (most recent call last):
  File "test2.py", line 23, in <module>
    out = d3graph(adjmat)
  File "C:\Users\marve\anaconda3\lib\site-packages\d3graph\d3graph.py", line 191, in d3graph
    _write_index_html(config, json_data)
  File "C:\Users\marve\anaconda3\lib\site-packages\d3graph\d3graph.py", line 274, in _write_index_html
    index_file.write_text(index_template.render(content))
  File "C:\Users\marve\anaconda3\lib\pathlib.py", line 1252, in write_text
    return f.write(data)
  File "C:\Users\marve\anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u03b5' in position 44258: character maps to <undefined>

I tried to reinstall the package but it doesn't help

**Comment by erdogant** [comment]
It seems that the issue is that the greek character epsilon is somewhere in your data frame.
I created a new version where I replace any of such chars in the column names into "_". Can you check whether this solves your issue because I'm not sure where exactly the char is located.

Update with:
`pip install -U d3graph
`

**Comment by marvensherif** [comment]
i tried new update but it give same error

**Comment by erdogant** [comment]
can you reproduce and post the error with a small example?

**Comment by marvensherif** [comment]
code:

from d3graph import d3graph, vec2adjmat
source = ['A','B','C']
target = ['G','A','D']
weight = [5.56, 0.5, 0.64]

adjmat = vec2adjmat(source, target, weight=weight)
out = d3graph(adjmat)


error:

[d3graph] >Removing special chars and replacing with "_"
C:\Users\marve\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
[d3graph] >Writing C:\Users\marve\Desktop\Term9\Graduation Project\index.html
Traceback (most recent call last):
  File "test2.py", line 23, in <module>
    out = d3graph(adjmat)
  File "C:\Users\marve\anaconda3\lib\site-packages\d3graph\d3graph.py", line 194, in d3graph
    _write_index_html(config, json_data)
  File "C:\Users\marve\anaconda3\lib\site-packages\d3graph\d3graph.py", line 275, in _write_index_html
    index_file.write_text(index_template.render(content))
  File "C:\Users\marve\anaconda3\lib\pathlib.py", line 1252, in write_text
    return f.write(data)
  File "C:\Users\marve\anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u03b5' in position 44258: character maps to <undefined>

**Comment by erdogant** [comment]
This issue is fixed, right?

https://github.com/erdogant/d3graph/issues/2

**Comment by marvensherif** [comment]
Yes,it was fixed thanks
